/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookRent;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    //edited---------------------------------------------------------------------------------
    //เชื่อมต่อข้อมูลใน DataBase
    ResultSet user = new DatabaseManagement().readCustomerDataBase();
    ResultSet staff = new DatabaseManagement().readPersonnelDataBase();
    //edited---------------------------------------------------------------------------------
    
    /**
     * Creates new form login
     */
    public login() {
        setUndecorated(true);
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0, 1200,740, 50,50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        login = new RoundedPanel (50, new Color(255,255,255));
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new RoundedPanel (50, new Color(102,102,255));
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookfly = new javax.swing.JLabel();
        tablogin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        footer.setBackground(new java.awt.Color(255, 102, 51));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Coolsville", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Faculty of Information Technology, King Mongkut's Institute of Technology Ladkrabang");
        footer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 0, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/it.png"))); // NOI18N
        footer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 0, -1, 40));

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 153));
        header.setPreferredSize(new java.awt.Dimension(1200, 40));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonclose(evt);
            }
        });
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, 38));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 0, -1, 38));

        jLabel10.setFont(new java.awt.Font("Coolsville", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BOOKRENT");
        header.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, -1, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoheader.png"))); // NOI18N
        header.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Angsana New", 0, 48))); // NOI18N
        login.setOpaque(false);
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 349, 75, 40));

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jLabel1.setText("Username");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 105, -1, -1));

        jTextField1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setName(""); // NOI18N
        login.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 159, 255, 40));

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jLabel2.setText("Password");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 206, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        login.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 260, 256, 40));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jButton2.setText("Register");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        login.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 349, 75, 40));

        main.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 360, 440));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Coolsville", 1, 54)); // NOI18N
        jLabel3.setText("BOOKRENT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 410, 60));

        main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 460, 90));

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jLabel5.setText("Welcome BookRent system Is a program that will allow users");
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jLabel4.setText("to Convenient to use It is the best system ever in the world.");
        main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        bookfly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.png"))); // NOI18N
        main.add(bookfly, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        tablogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        tablogin.setText("jLabel1");
        main.add(tablogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 600, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroud.png"))); // NOI18N
        main.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonclose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonclose
        dispose();
    }//GEN-LAST:event_buttonclose

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        //edited---------------------------------------------------------------------------------
        //เช็ค username กับ passwords ในตารางของข้อมูล Customer ใน DataBase
        String txt1 = jTextField1.getText();
        String txt2 = jPasswordField1.getText();
        
        int status = 0; //ตัวแปรที่ใช้เช็คว่าใครเป็นคน login เข้ามา
        // status = 0 คือ ไม่เจอข้อมูล
        // status = 1 คือ Personnel
        // status = 2 คือ Customer
        // status = 3 คือ Admin
        
        try {
            //เช็ค Personnel
            staff.beforeFirst();
            while(staff.next()){
                if(staff.getString(2).equals(txt1) && staff.getString(3).equals(txt2)){
                    ShareMethod.setFirstName(staff.getString(4));
                    ShareMethod.setLastName(staff.getString(5));
                    ShareMethod.setUsername(staff.getString(2));
                    status = 1;
                }
            }
            staff.beforeFirst();
            
            //เช็ค Customer
            user.beforeFirst();
            while(user.next()){
                if(user.getString(2).equals(txt1) && user.getString(3).equals(txt2)){
                    ShareMethod.setFirstName(user.getString(4));
                    ShareMethod.setLastName(user.getString(5));
                    ShareMethod.setUsername(user.getString(2));
                    status = 2;
                }
            }
            user.beforeFirst();
            
            //เช็ค Admin และ Set
            String admin = "admin";
            String pass = "0000";
            if(txt1.equals(admin) && txt2.equals(pass)){
                ShareMethod.setFirstName("Admin");
                ShareMethod.setLastName("");
                ShareMethod.setUsername("admin");
                status = 3;
            }
            
            //เปิดหน้าต่างใหม่ตามผู้ใช้ที่ login เข้ามา
            if(status == 0){
                JOptionPane.showMessageDialog(null, "Username or Passwords Invalid.");
            }else if(status == 1){
                new staff().setVisible(true);
                this.dispose();
            }else if(status == 2){
                new user().setVisible(true);
                this.dispose();
            }else if(status == 3){
                new admin().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
        }
        //edited---------------------------------------------------------------------------------
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        

        //edited---------------------------------------------------------------------------------
        new register().setVisible(true);
        this.dispose();
        //edited---------------------------------------------------------------------------------
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    int x, y;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bookfly;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel login;
    private javax.swing.JPanel main;
    private javax.swing.JLabel tablogin;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//            
        }
    }
}
