/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookRent;

/**
 *
 * @author User
 */
public class staff extends javax.swing.JFrame {

    /**
     * Creates new form staff
     */
    public staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staff_main = new javax.swing.JPanel();
        staff_slidetab = new javax.swing.JPanel();
        staff_tab_welocme = new javax.swing.JPanel();
        staff_tab_library = new javax.swing.JPanel();
        staff_txt_liblrary = new javax.swing.JLabel();
        staff_tab_rent = new javax.swing.JPanel();
        staff_txt_rent = new javax.swing.JLabel();
        staff_tab_return = new javax.swing.JPanel();
        staff_txt_return = new javax.swing.JLabel();
        staff_tab_user = new javax.swing.JPanel();
        staff_txt_user = new javax.swing.JLabel();
        staff_tab_empty1 = new javax.swing.JPanel();
        staff_tab_empty2 = new javax.swing.JPanel();
        staff_tab_logout = new javax.swing.JPanel();
        staff_txt_logout = new javax.swing.JLabel();
        staff_multipanel = new javax.swing.JPanel();
        staff_panel_welcome = new javax.swing.JPanel();
        staff_panel_library = new javax.swing.JPanel();
        staff_panel_rent = new javax.swing.JPanel();
        staff_panel_return = new javax.swing.JPanel();
        staff_panel_user = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookRent");
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        staff_main.setBackground(new java.awt.Color(255, 255, 153));
        staff_main.setMaximumSize(new java.awt.Dimension(1000, 700));
        staff_main.setMinimumSize(new java.awt.Dimension(1000, 700));

        staff_slidetab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        staff_slidetab.setMaximumSize(new java.awt.Dimension(200, 700));
        staff_slidetab.setMinimumSize(new java.awt.Dimension(200, 700));

        staff_tab_welocme.setBackground(new java.awt.Color(255, 204, 102));
        staff_tab_welocme.setMaximumSize(new java.awt.Dimension(200, 140));
        staff_tab_welocme.setMinimumSize(new java.awt.Dimension(200, 140));

        javax.swing.GroupLayout staff_tab_welocmeLayout = new javax.swing.GroupLayout(staff_tab_welocme);
        staff_tab_welocme.setLayout(staff_tab_welocmeLayout);
        staff_tab_welocmeLayout.setHorizontalGroup(
            staff_tab_welocmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        staff_tab_welocmeLayout.setVerticalGroup(
            staff_tab_welocmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        staff_tab_library.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_library.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_library.setMinimumSize(new java.awt.Dimension(200, 80));

        staff_txt_liblrary.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        staff_txt_liblrary.setText("Library");

        javax.swing.GroupLayout staff_tab_libraryLayout = new javax.swing.GroupLayout(staff_tab_library);
        staff_tab_library.setLayout(staff_tab_libraryLayout);
        staff_tab_libraryLayout.setHorizontalGroup(
            staff_tab_libraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_tab_libraryLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(staff_txt_liblrary)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        staff_tab_libraryLayout.setVerticalGroup(
            staff_tab_libraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_txt_liblrary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        staff_tab_rent.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_rent.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_rent.setMinimumSize(new java.awt.Dimension(200, 80));
        staff_tab_rent.setPreferredSize(new java.awt.Dimension(200, 80));

        staff_txt_rent.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        staff_txt_rent.setText("Rent");

        javax.swing.GroupLayout staff_tab_rentLayout = new javax.swing.GroupLayout(staff_tab_rent);
        staff_tab_rent.setLayout(staff_tab_rentLayout);
        staff_tab_rentLayout.setHorizontalGroup(
            staff_tab_rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_tab_rentLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(staff_txt_rent)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        staff_tab_rentLayout.setVerticalGroup(
            staff_tab_rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_txt_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        staff_tab_return.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_return.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_return.setMinimumSize(new java.awt.Dimension(200, 80));

        staff_txt_return.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        staff_txt_return.setText("Return");

        javax.swing.GroupLayout staff_tab_returnLayout = new javax.swing.GroupLayout(staff_tab_return);
        staff_tab_return.setLayout(staff_tab_returnLayout);
        staff_tab_returnLayout.setHorizontalGroup(
            staff_tab_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_tab_returnLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(staff_txt_return)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        staff_tab_returnLayout.setVerticalGroup(
            staff_tab_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_txt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        staff_tab_user.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_user.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_user.setMinimumSize(new java.awt.Dimension(200, 80));
        staff_tab_user.setPreferredSize(new java.awt.Dimension(200, 80));

        staff_txt_user.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        staff_txt_user.setText("User");

        javax.swing.GroupLayout staff_tab_userLayout = new javax.swing.GroupLayout(staff_tab_user);
        staff_tab_user.setLayout(staff_tab_userLayout);
        staff_tab_userLayout.setHorizontalGroup(
            staff_tab_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_tab_userLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(staff_txt_user)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        staff_tab_userLayout.setVerticalGroup(
            staff_tab_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_txt_user, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        staff_tab_empty1.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_empty1.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_empty1.setMinimumSize(new java.awt.Dimension(200, 80));

        javax.swing.GroupLayout staff_tab_empty1Layout = new javax.swing.GroupLayout(staff_tab_empty1);
        staff_tab_empty1.setLayout(staff_tab_empty1Layout);
        staff_tab_empty1Layout.setHorizontalGroup(
            staff_tab_empty1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        staff_tab_empty1Layout.setVerticalGroup(
            staff_tab_empty1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        staff_tab_empty2.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_empty2.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_empty2.setMinimumSize(new java.awt.Dimension(200, 80));

        javax.swing.GroupLayout staff_tab_empty2Layout = new javax.swing.GroupLayout(staff_tab_empty2);
        staff_tab_empty2.setLayout(staff_tab_empty2Layout);
        staff_tab_empty2Layout.setHorizontalGroup(
            staff_tab_empty2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        staff_tab_empty2Layout.setVerticalGroup(
            staff_tab_empty2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        staff_tab_logout.setBackground(new java.awt.Color(255, 204, 0));
        staff_tab_logout.setMaximumSize(new java.awt.Dimension(200, 80));
        staff_tab_logout.setMinimumSize(new java.awt.Dimension(200, 80));
        staff_tab_logout.setPreferredSize(new java.awt.Dimension(200, 80));

        staff_txt_logout.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        staff_txt_logout.setText("Logout");

        javax.swing.GroupLayout staff_tab_logoutLayout = new javax.swing.GroupLayout(staff_tab_logout);
        staff_tab_logout.setLayout(staff_tab_logoutLayout);
        staff_tab_logoutLayout.setHorizontalGroup(
            staff_tab_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_tab_logoutLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(staff_txt_logout)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        staff_tab_logoutLayout.setVerticalGroup(
            staff_tab_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_txt_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout staff_slidetabLayout = new javax.swing.GroupLayout(staff_slidetab);
        staff_slidetab.setLayout(staff_slidetabLayout);
        staff_slidetabLayout.setHorizontalGroup(
            staff_slidetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_tab_welocme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_rent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_return, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_empty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_empty2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_tab_library, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        staff_slidetabLayout.setVerticalGroup(
            staff_slidetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_slidetabLayout.createSequentialGroup()
                .addComponent(staff_tab_welocme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_library, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_rent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_empty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_empty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_tab_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        staff_multipanel.setBackground(new java.awt.Color(255, 255, 153));
        staff_multipanel.setMaximumSize(new java.awt.Dimension(800, 700));
        staff_multipanel.setMinimumSize(new java.awt.Dimension(800, 700));
        staff_multipanel.setLayout(new java.awt.CardLayout());

        staff_panel_welcome.setBackground(new java.awt.Color(255, 255, 153));
        staff_panel_welcome.setMaximumSize(new java.awt.Dimension(800, 700));
        staff_panel_welcome.setMinimumSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout staff_panel_welcomeLayout = new javax.swing.GroupLayout(staff_panel_welcome);
        staff_panel_welcome.setLayout(staff_panel_welcomeLayout);
        staff_panel_welcomeLayout.setHorizontalGroup(
            staff_panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        staff_panel_welcomeLayout.setVerticalGroup(
            staff_panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        staff_multipanel.add(staff_panel_welcome, "card2");

        staff_panel_library.setBackground(new java.awt.Color(255, 255, 153));
        staff_panel_library.setMaximumSize(new java.awt.Dimension(800, 700));
        staff_panel_library.setMinimumSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout staff_panel_libraryLayout = new javax.swing.GroupLayout(staff_panel_library);
        staff_panel_library.setLayout(staff_panel_libraryLayout);
        staff_panel_libraryLayout.setHorizontalGroup(
            staff_panel_libraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        staff_panel_libraryLayout.setVerticalGroup(
            staff_panel_libraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        staff_multipanel.add(staff_panel_library, "card3");

        staff_panel_rent.setBackground(new java.awt.Color(255, 255, 153));
        staff_panel_rent.setMaximumSize(new java.awt.Dimension(800, 700));
        staff_panel_rent.setMinimumSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout staff_panel_rentLayout = new javax.swing.GroupLayout(staff_panel_rent);
        staff_panel_rent.setLayout(staff_panel_rentLayout);
        staff_panel_rentLayout.setHorizontalGroup(
            staff_panel_rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        staff_panel_rentLayout.setVerticalGroup(
            staff_panel_rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        staff_multipanel.add(staff_panel_rent, "card4");

        staff_panel_return.setBackground(new java.awt.Color(255, 255, 153));
        staff_panel_return.setMaximumSize(new java.awt.Dimension(800, 700));
        staff_panel_return.setMinimumSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout staff_panel_returnLayout = new javax.swing.GroupLayout(staff_panel_return);
        staff_panel_return.setLayout(staff_panel_returnLayout);
        staff_panel_returnLayout.setHorizontalGroup(
            staff_panel_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        staff_panel_returnLayout.setVerticalGroup(
            staff_panel_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        staff_multipanel.add(staff_panel_return, "card5");

        staff_panel_user.setBackground(new java.awt.Color(255, 255, 153));
        staff_panel_user.setMaximumSize(new java.awt.Dimension(800, 700));
        staff_panel_user.setMinimumSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout staff_panel_userLayout = new javax.swing.GroupLayout(staff_panel_user);
        staff_panel_user.setLayout(staff_panel_userLayout);
        staff_panel_userLayout.setHorizontalGroup(
            staff_panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        staff_panel_userLayout.setVerticalGroup(
            staff_panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        staff_multipanel.add(staff_panel_user, "card6");

        javax.swing.GroupLayout staff_mainLayout = new javax.swing.GroupLayout(staff_main);
        staff_main.setLayout(staff_mainLayout);
        staff_mainLayout.setHorizontalGroup(
            staff_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_mainLayout.createSequentialGroup()
                .addComponent(staff_slidetab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staff_multipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        staff_mainLayout.setVerticalGroup(
            staff_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_slidetab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(staff_multipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel staff_main;
    private javax.swing.JPanel staff_multipanel;
    private javax.swing.JPanel staff_panel_library;
    private javax.swing.JPanel staff_panel_rent;
    private javax.swing.JPanel staff_panel_return;
    private javax.swing.JPanel staff_panel_user;
    private javax.swing.JPanel staff_panel_welcome;
    private javax.swing.JPanel staff_slidetab;
    private javax.swing.JPanel staff_tab_empty1;
    private javax.swing.JPanel staff_tab_empty2;
    private javax.swing.JPanel staff_tab_library;
    private javax.swing.JPanel staff_tab_logout;
    private javax.swing.JPanel staff_tab_rent;
    private javax.swing.JPanel staff_tab_return;
    private javax.swing.JPanel staff_tab_user;
    private javax.swing.JPanel staff_tab_welocme;
    private javax.swing.JLabel staff_txt_liblrary;
    private javax.swing.JLabel staff_txt_logout;
    private javax.swing.JLabel staff_txt_rent;
    private javax.swing.JLabel staff_txt_return;
    private javax.swing.JLabel staff_txt_user;
    // End of variables declaration//GEN-END:variables
}
