/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookRent;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    //edited---------------------------------------------------------------------------------
    //เชื่อมต่อข้อมูลใน DataBase
    ResultSet user = new DatabaseManagement().readCustomerDataBase();
    ResultSet staff = new DatabaseManagement().readPersonnelDataBase();
    //edited---------------------------------------------------------------------------------
    
    /**
     * Creates new form login
     */
    public login() {
        setUndecorated(true);
        initComponents();
        setVisible(true);
        //menubar mini = new menubar();
        //mini.setVisible(true);
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0, 1200,740, 50,50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        txtfooter = new javax.swing.JLabel();
        logofooter = new javax.swing.JLabel();
        menubar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        login = new RoundedPanel (50, new Color(255,255,255));
        btmlogin = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btmregister = new javax.swing.JButton();
        bookrent = new RoundedPanel (50, new Color(102,102,255));
        txtbookrent = new javax.swing.JLabel();
        describe1 = new javax.swing.JLabel();
        describe2 = new javax.swing.JLabel();
        bookfly = new javax.swing.JLabel();
        tablogin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer.setBackground(new java.awt.Color(255, 102, 51));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfooter.setFont(new java.awt.Font("Coolsville", 0, 16)); // NOI18N
        txtfooter.setForeground(new java.awt.Color(255, 255, 255));
        txtfooter.setText("Faculty of Information Technology, King Mongkut's Institute of Technology Ladkrabang");
        footer.add(txtfooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        logofooter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/it.png"))); // NOI18N
        footer.add(logofooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        main.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1200, -1));

        menubar.setBackground(new java.awt.Color(0, 0, 153));
        menubar.setPreferredSize(new java.awt.Dimension(1200, 40));
        menubar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menubarMouseDragged(evt);
            }
        });
        menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menubarMousePressed(evt);
            }
        });
        menubar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonclose(evt);
            }
        });
        menubar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, 38));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        menubar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 0, -1, 38));

        title.setFont(new java.awt.Font("Coolsville", 0, 16)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("BOOKRENT");
        menubar.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, -1, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoheader.png"))); // NOI18N
        menubar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        main.add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Angsana New", 0, 48))); // NOI18N
        login.setOpaque(false);
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmlogin.setBackground(new java.awt.Color(255, 204, 0));
        btmlogin.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        btmlogin.setText("Login");
        btmlogin.setBorder(null);
        btmlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmloginActionPerformed(evt);
            }
        });
        login.add(btmlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 349, 75, 40));

        username.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        username.setText("Username");
        login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 105, -1, -1));

        txtusername.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtusername.setName(""); // NOI18N
        login.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 159, 255, 40));

        password.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        password.setText("Password");
        login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 206, -1, -1));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        login.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 260, 256, 40));

        btmregister.setBackground(new java.awt.Color(255, 204, 0));
        btmregister.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        btmregister.setText("Register");
        btmregister.setBorder(null);
        btmregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmregister.setPreferredSize(new java.awt.Dimension(53, 29));
        btmregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmregisterActionPerformed(evt);
            }
        });
        login.add(btmregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 349, 75, 40));

        main.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 360, 440));

        bookrent.setBackground(new java.awt.Color(102, 102, 255));
        bookrent.setOpaque(false);
        bookrent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbookrent.setFont(new java.awt.Font("Coolsville", 1, 54)); // NOI18N
        txtbookrent.setText("BOOKRENT");
        bookrent.add(txtbookrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 410, 60));

        main.add(bookrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 460, 90));

        describe1.setFont(new java.awt.Font("Angsana New", 3, 28)); // NOI18N
        describe1.setText("\"Welcome BookRent system Is a program that will allow users");
        main.add(describe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        describe2.setFont(new java.awt.Font("Angsana New", 3, 28)); // NOI18N
        describe2.setText("to Convenient to use It is the best system ever in the world.\"");
        main.add(describe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        bookfly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.png"))); // NOI18N
        main.add(bookfly, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        tablogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        tablogin.setText("jLabel1");
        main.add(tablogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 600, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroud.png"))); // NOI18N
        main.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmloginActionPerformed
        

        //edited---------------------------------------------------------------------------------
        //เช็ค username กับ passwords ในตารางของข้อมูล Customer ใน DataBase
        String txt1 = txtusername.getText();
        String txt2 = txtpassword.getText();
        
        int status = 0; //ตัวแปรที่ใช้เช็คว่าใครเป็นคน login เข้ามา
        // status = 0 คือ ไม่เจอข้อมูล
        // status = 1 คือ Personnel
        // status = 2 คือ Customer
        // status = 3 คือ Admin
        
        try {
            //เช็ค Personnel
            staff.beforeFirst();
            while(staff.next()){
                if(staff.getString(2).equals(txt1) && staff.getString(3).equals(txt2)){
                    ShareMethod.setFirstName(staff.getString(4));
                    ShareMethod.setLastName(staff.getString(5));
                    ShareMethod.setUsername(staff.getString(2));
                    status = 1;
                }
            }
            staff.beforeFirst();
            
            //เช็ค Customer
            user.beforeFirst();
            while(user.next()){
                if(user.getString(2).equals(txt1) && user.getString(3).equals(txt2)){
                    ShareMethod.setFirstName(user.getString(4));
                    ShareMethod.setLastName(user.getString(5));
                    ShareMethod.setUsername(user.getString(2));
                    status = 2;
                }
            }
            user.beforeFirst();
            
            //เช็ค Admin และ Set
            String admin = "admin";
            String pass = "0000";
            if(txt1.equals(admin) && txt2.equals(pass)){
                ShareMethod.setFirstName("Admin");
                ShareMethod.setLastName("");
                ShareMethod.setUsername("admin");
                status = 3;
            }
            
            //เปิดหน้าต่างใหม่ตามผู้ใช้ที่ login เข้ามา
            if(status == 0){
                JOptionPane.showMessageDialog(null, "Username or Passwords Invalid.");
            }else if(status == 1){
                new staff().setVisible(true);
                this.dispose();
            }else if(status == 2){
                new user().setVisible(true);
                this.dispose();
            }else if(status == 3){
                new admin().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
        }
        //edited---------------------------------------------------------------------------------
        
        
    }//GEN-LAST:event_btmloginActionPerformed

    private void btmregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmregisterActionPerformed
        

        //edited---------------------------------------------------------------------------------
        new register().setVisible(true);
        this.dispose();
        //edited---------------------------------------------------------------------------------
        
        
    }//GEN-LAST:event_btmregisterActionPerformed

    private void closebuttonclose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonclose
        dispose();
    }//GEN-LAST:event_closebuttonclose
    int x, y;
    private void menubarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_menubarMouseDragged

    private void menubarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_menubarMousePressed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        //this.setState(menubar.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bookfly;
    private javax.swing.JPanel bookrent;
    private javax.swing.JButton btmlogin;
    private javax.swing.JButton btmregister;
    private javax.swing.JLabel close;
    private javax.swing.JLabel describe1;
    private javax.swing.JLabel describe2;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logofooter;
    private javax.swing.JPanel main;
    private javax.swing.JPanel menubar;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel password;
    private javax.swing.JLabel tablogin;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtbookrent;
    private javax.swing.JLabel txtfooter;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//            
        }
    }
}
