/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookRent;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class register extends javax.swing.JFrame {

    
    //edited---------------------------------------------------------------------------------
    ResultSet customer = new DatabaseManagement().readCustomerDataBase();
    DatabaseManagement db = new DatabaseManagement();
    ShareMethod sm = new ShareMethod();
    //edited---------------------------------------------------------------------------------
    
    
    /**
     * Creates new form register
     */
    public register() {
        setUndecorated(true);
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0, 1200,740, 50,50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        bookfly = new javax.swing.JLabel();
        register = new RoundedPanel (30, new Color(255,255,166));
        head = new RoundedPanel (30, new Color(102,102,255));
        txthead = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        confirm = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JPasswordField();
        email = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btmregister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menubar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookfly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.png"))); // NOI18N
        main.add(bookfly, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        register.setBackground(new java.awt.Color(255, 255, 166));
        register.setOpaque(false);
        register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setOpaque(false);
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txthead.setBackground(new java.awt.Color(102, 102, 255));
        txthead.setFont(new java.awt.Font("Coolsville", 1, 54)); // NOI18N
        txthead.setText("REGISTER");
        head.add(txthead, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 0, 975, -1));

        register.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        firstname.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        firstname.setText("Firstname");
        register.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 107, -1, -1));

        lastname.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        lastname.setText("Lastname");
        register.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 107, -1, -1));

        txtfirstname.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        txtfirstname.setPreferredSize(new java.awt.Dimension(6, 50));
        register.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 152, 350, 40));

        txtlastname.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        txtlastname.setToolTipText("");
        txtlastname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtlastname.setPreferredSize(new java.awt.Dimension(6, 50));
        register.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 152, 350, 40));

        username.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        username.setText("Username");
        username.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        register.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 210, -1, -1));

        txtusername.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        txtusername.setPreferredSize(new java.awt.Dimension(6, 50));
        register.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 255, 350, 40));

        password.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        password.setText("Password");
        password.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        register.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 210, -1, -1));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        register.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 255, 350, 40));

        confirm.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        confirm.setText("Confirm Password");
        confirm.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        register.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 313, -1, -1));

        txtconfirm.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        register.add(txtconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 358, 350, 40));

        email.setFont(new java.awt.Font("Angsana New", 0, 32)); // NOI18N
        email.setText("E - mail");
        email.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        register.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 313, -1, -1));

        txtemail.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        txtemail.setPreferredSize(new java.awt.Dimension(6, 50));
        register.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 358, 350, 40));

        btmregister.setBackground(new java.awt.Color(255, 204, 0));
        btmregister.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        btmregister.setText("Register");
        btmregister.setBorder(null);
        btmregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmregisterActionPerformed(evt);
            }
        });
        register.add(btmregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 90, 40));

        main.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1090, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroud.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menubar.setBackground(new java.awt.Color(0, 0, 153));
        menubar.setPreferredSize(new java.awt.Dimension(1200, 40));
        menubar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menubarMouseDragged(evt);
            }
        });
        menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menubarMousePressed(evt);
            }
        });
        menubar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonclose(evt);
            }
        });
        menubar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, 38));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        menubar.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 0, -1, 38));

        title.setFont(new java.awt.Font("Coolsville", 0, 16)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("BOOKRENT");
        menubar.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, -1, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoheader.png"))); // NOI18N
        menubar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menubar, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmregisterActionPerformed
        
        //edited---------------------------------------------------------------------------------
        String firstName = txtfirstname.getText();
        String lastName = txtlastname.getText();
        String userName = txtusername.getText();
        String pass = txtpassword.getText();
        String conPass = txtconfirm.getText();
        String email = txtemail.getText();
        int chak = 0, var = 0, num = 0;
        //เช็คว่า username ซ้ำกันหรือไม่จากข้อมูลใน DataBase
        if (firstName.equals(""))
            num++;
        if (lastName.equals(""))
            num++;
        if (userName.equals(""))
            num++;
        if (pass.equals(""))
            num++;
        if (conPass.equals(""))
            num++;
        if (email.equals(""))
            num++;
        
        try {
            //เช็คว่า username ซ้ำกันหรือไม่จากข้อมูลใน DataBase
            customer.beforeFirst();
            while(customer.next()){
                if(customer.getString(2).equals(userName)){
                    chak = 1;
                    var = 1;
                }
            }
            customer.beforeFirst();
            
            //เช็ค username กับ passwords
            if(num != 0){
                JOptionPane.showMessageDialog(null, "Complete the form!!!");
            }else{
                if(chak == 1){
                    JOptionPane.showMessageDialog(null, "Username Invalid!!!");
                }
                if(pass.equals(conPass) == false){
                    chak = 2;
                }
                if(chak == 2 && var == 0){
                    JOptionPane.showMessageDialog(null, "Passwords Invalid!!!");
                }
            }
            if (num == 0 && chak == 0){
                String[] str = {txtusername.getText(), txtpassword.getText(), txtfirstname.getText(), txtlastname.getText(), "0", "0"};
                db.insertCustomerDataBase(str, sm.findAmountOfCustomer()+1);
                JOptionPane.showMessageDialog(null, "Register Done.");
                new login().setVisible(true);
                this.dispose();
            }
                        
        } catch (Exception e) {
        }
        //edited---------------------------------------------------------------------------------        
        
    }//GEN-LAST:event_btmregisterActionPerformed

    private void closebuttonclose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonclose
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_closebuttonclose

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        //this.setState(menubar.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked
    int x, y;
    private void menubarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_menubarMouseDragged

    private void menubarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_menubarMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookfly;
    private javax.swing.JButton btmregister;
    private javax.swing.JLabel close;
    private javax.swing.JLabel confirm;
    private javax.swing.JLabel email;
    private javax.swing.JLabel firstname;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main;
    private javax.swing.JPanel menubar;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel password;
    private javax.swing.JPanel register;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txtconfirm;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JLabel txthead;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//            
        }
    }
}
